CREATE DATABASE LIVRARIA;
USE LIVRARIA;
CREATE TABLE LIVRO (
NOME VARCHAR (30),
AUTOR VARCHAR (30),
SEXO VARCHAR (9),
PAGINAS INT (5),
EDITORA VARCHAR (30),
VALOR FLOAT (5),
ESTADO CHAR (2),
ANO INT (5));

/*ANA CLAUDIA*/
INSERT INTO LIVRO(NOME,AUTOR,SEXO,PAGINAS,EDITORA,VALOR,ESTADO,ANO) VALUES('CAVALEIRO REAL','ANA CLAUDIA','FEMININO',465,'ATLAS',49.90,'RJ','2009');


/*JOÃO NUNES*/
INSERT INTO LIVRO(NOME,AUTOR,SEXO,PAGINAS,EDITORA,VALOR,ESTADO,ANO) VALUES('SQL PARA LEIGOS','JOAO NUNES','MASCULINO',450,'ADDISON',98,'SP','2018');

/*CELIA TAVARES*/
INSERT INTO LIVRO(NOME,AUTOR,SEXO,PAGINAS,EDITORA,VALOR,ESTADO,ANO) VALUES('RECEITAS CASEIRAS','CELIA TAVARES', 'FEMININO',210, 'ATLAS',45,'RJ','2008');

/* EDUARDO SANTOS*/
INSERT INTO LIVRO(NOME,AUTOR,SEXO,PAGINAS,EDITORA,VALOR,ESTADO,ANO) VALUES('PESSOAS EFETIVAS', 'EDUARDO SANTOS', 'MASCULINO',390,'BETA', 78.99, 'RJ', '2018');

INSERT INTO LIVRO(NOME,AUTOR,SEXO,PAGINAS,EDITORA,VALOR,ESTADO,ANO) VALUES('HABITOS SAUDAVEIS', 'EDUARDDO SANTOS','MASCULINO',630,'BETA',150.98,'RJ','2019');

/*HERMES MACEDO*/
INSERT INTO LIVRO(NOME,AUTOR,SEXO,PAGINAS,EDITORA,VALOR,ESTADO,ANO) VALUES('A CASA MARROM','HERMES MACEDO','MASCULINO',250,'BUBBA',60,'MG','2016');

/*GERALDO FRANCISCO*/
INSERT INTO LIVRO(NOME,AUTOR,SEXO,PAGINAS,EDITORA,VALOR,ESTADO,ANO) VALUES('ESTACIO QUERIDO','GERALDO FRANCISCO','MASCULINO',310, 'INSIGNIA',100,'ES', '2015');

/*LEDA SILVA*/
INSERT INTO LIVRO(NOME,AUTOR,SEXO,PAGINAS,EDITORA,VALOR,ESTADO,ANO) VALUES('PRA SEMPRE AMIGAS','LEDA SILVA','FEMININO',510,'INSIGNIA',78.98,'ES','2011');

/*MARCO ALCANTRA*/
INSERT INTO LIVRO(NOME,AUTOR,SEXO,PAGINAS,EDITORA,VALOR,ESTADO,ANO) VALUES('COPAS INESQUECIVEIS','MARCO ALCANTRA','MASCULINO',200,'LARSON',130.98,'RS','2018');

/*ANA MAFRA*/
INSERT INTO LIVRO(NOME,AUTOR,SEXO,PAGINAS,EDITORA,VALOR,ESTADO,ANO) VALUES('O PODER DA MENTE','CLARA MAFRA','FEMININO',120,'CONTINENTAL',56.58,'SP','2017');
/*TRAZENDO TODOS OS DADOS*/
SELECT*FROM LIVRO;
/*TRAZENDO NOME DO LIVRO E DA EDITORA*/
SELECT NOME, EDITORA FROM LIVRO;
/*TRAZENDO NOME DO LIVRO E O ESTADO DE AUTORES MASCULINOS*/
SELECT NOME, ESTADO FROM LIVRO WHERE SEXO = 'MASCULINO';
/*TRAZENDO O NOME DO LIVRO E O NUMERO DE PAGINAS DE LIVROS PUBLICADOS POR AUTORAS FEMININAS*/
SELECT NOME, PAGINAS FROM LIVRO WHERE SEXO = 'F';
/*VALORES DOS LIVROS EDITORAS DE SAO PAULO*/
SELECT VALOR FROM LIVRO WHERE ESTADO = 'SP';
SELECT AUTOR, SEXO FROM LIVRO WHERE SEXO = 'MASCULINO' AND (ESTADO = 'SP' OR ESTADO = 'RJ');